### ISSUE TITLE
Build CI/CD pipeline so that .py files convert to .ipynb automatically

### ISSUE THREAD

**Issue by jmunroe** [ScienceCore/climaterisk#40]
We are using `jupytext` to commit .py files to our repo instead on having to have issues with version control of .ipynb.

Task: build out the necessary GitHub action to run `jupytext`

**Comment by jnywong** [comment]
I think this issue is now superseded by https://github.com/ScienceCore/climaterisk/issues/59

> - Convert all existing notebook (i.e., .ipynb) files to MarkDown (.md) files

and I think we don't actually need to [trigger code execution](https://jupyterbook.org/en/stable/content/execute.html) during the CI/CD to build the Jupyter Book.

This task has a dependency on https://github.com/ScienceCore/climaterisk/issues/59, so I will pick this up again when that work is complete.

**Comment by jnywong** [comment]
Content is being written in markdown only and checked into version control. Marking this as done.
